---
output:
  pdf_document: default
  html_document: default
---
Install the packages 
```{r}
install.packages("ggplot2", "palmerpenguins", "janitor", "dplyr", "tinytex", "ragg")
```


Load the packages
```{r}
library(ggplot2)
library(palmerpenguins)
library(janitor)
library(dplyr)
library(tinytex)
library(ragg)
```

Load the function definitions 
```{r}
source("functions/cleaning.r")
source("functions/plotting.r")
```

Save & check the raw data
```{r}
write.csv(penguins_raw, "data/penguins_raw.csv")
names(penguins_raw)
```

Clean the data
```{r}
penguins_clean <- penguins_raw %>%
    clean_column_names() %>%
    shorten_species() %>%
    remove_empty_columns_rows()

names(penguins_clean)
```

Save cleaned data
```{r}
write.csv(penguins_clean, "data/penguins_clean.csv")
```

Filter the data
```{r}
body_mass_vs_flipper_length_data <- penguins_clean %>%
    subset_columns(c("flipper_length_mm", "body_mass_g", "species","sex")) %>%  #only show columns with desired titles 
    remove_NA()

head(body_mass_vs_flipper_length_data)
```

Plot the data (explanatory figure)
```{r}
penguin_scatterplot <- ggplot(data = body_mass_vs_flipper_length_data, 
                              aes(x = body_mass_g, 
                                  y = flipper_length_mm,
                                  colour = species)) +
  geom_point(size = 2, alpha = 0.5) +
  labs(title = " Scatter Plot of Body Mass vs. Flipper length", 
       x = "Body mass (g)", 
       y = "Flipper length (mm)") +
  scale_color_manual(values = c("darkorange","darkviolet","darkgreen")) +
    theme_bw() 

penguin_scatterplot
```

Save explanatory figure
```{r}
pdf("Figures/BodyMass_vs_FlipperLength.pdf", 
        width = 5.9, height = 5.9)
penguin_scatterplot
dev.off()
```

Statistical test (correlation test)
```{r}
correlation_test <- cor.test(body_mass_vs_flipper_length_data$body_mass_g, body_mass_vs_flipper_length_data$body_mass_g)
print(correlation_test)
```

Create results figure
```{r}
results_figure <- ggplot(body_mass_vs_flipper_length_data,
                        aes(x =body_mass_g, 
                            y = flipper_length_mm,
                            colour = species)) +
  geom_point(size = 2, alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE, colour = "black") +  # add a regression line 
  labs(title = "Scatter Plot of Body Mass vs. Flipper length", 
       x = "Body mass (g)", 
       y = "Flipper length (mm)") +
  scale_color_manual(values = c("darkorange","darkviolet","darkgreen")) +
  
  annotate("text", x = mean(body_mass_vs_flipper_length_data$body_mass_g),  # annotate plot with correlation coefficient & p-value
           y = max(body_mass_vs_flipper_length_data$flipper_length_mm), 
                          label = paste("correlation = ",
                                        round(correlation_test$estimate, 2),
                                        "\np-value = ",
                                        format(correlation_test$p.value,
                                               scientific = TRUE))) +
    theme_bw() 
results_figure
```

Save results figure
```{r}
pdf("Figures/results_figure.pdf", 
        width = 5.9, height = 5.9)
results_figure
dev.off()
```












